# Generated by Django 3.2 on 2021-05-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='RoleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.lob'),
        ),
    ]
