# Generated by Django 3.2 on 2021-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_userrole_roleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mev',
            fields=[
                ('Year', models.IntegerField()),
                ('GDP', models.IntegerField()),
                ('Inflation', models.IntegerField()),
                ('Interest_rate', models.IntegerField()),
                ('Domestic_credit_growth', models.IntegerField()),
                ('Dummy_var', models.IntegerField()),
                ('Reporting_date', models.CharField(max_length=100)),
                ('LOB', models.CharField(max_length=100)),
                ('Upload_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MevVar',
            fields=[
                ('Micro_Economic_variable', models.CharField(max_length=200)),
                ('Best_case', models.FloatField()),
                ('Worst_case', models.FloatField()),
                ('Reporting_date', models.CharField(max_length=100)),
                ('LOB', models.CharField(max_length=100)),
                ('Upload_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MicroPair',
            fields=[
                ('Pair', models.CharField(max_length=100)),
                ('Variable_1', models.CharField(max_length=100)),
                ('Variable_2', models.CharField(max_length=100)),
                ('Reporting_date', models.CharField(max_length=100)),
                ('LOB', models.CharField(max_length=100)),
                ('Upload_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
