# Generated by Django 3.2 on 2021-05-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_mev_mevvar_micropair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Input',
            fields=[
                ('variable', models.CharField(max_length=200)),
                ('input2', models.FloatField()),
                ('Reporting_date', models.CharField(max_length=100)),
                ('LOB', models.CharField(max_length=100)),
                ('Upload_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
