# Generated by Django 3.2 on 2021-05-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_other_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other_Input',
            new_name='OtherInput',
        ),
        migrations.RenameField(
            model_name='otherinput',
            old_name='input2',
            new_name='input',
        ),
    ]
