# Generated by Django 3.2 on 2021-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20210525_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hfc_Status_Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoB', models.CharField(max_length=100)),
                ('Report_date', models.CharField(max_length=50)),
                ('Flag', models.CharField(max_length=50)),
            ],
        ),
    ]
